/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-21 11:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.domain.Message;
import java.util.List;
import com.smhrd.domain.MessageDAO;
import com.smhrd.domain.Member;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.smhrd.domain.Member");
    _jspx_imports_classes.add("com.smhrd.domain.Message");
    _jspx_imports_classes.add("com.smhrd.domain.MessageDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>봄이 오겠조</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/popup.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/mainphoto.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"dist/needpopup.min.css\">\r\n");
      out.write("<script src=\"jquery-3.4.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta content=\"BlendTrans(Duration=0.2)\" http-equiv=\"Page-Enter\">\r\n");
      out.write("<meta content=\"BlendTrans(Duration=0.2)\" http-equiv=\"Page-exit\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("   <div id=\"header\">\r\n");
      out.write("      <div class=\"top\">\r\n");
      out.write("        <!-- Logo -->\r\n");
      out.write("         <div id=\"logo\">\r\n");
      out.write("            <span class=\"image avatar48\"><img src=\"images/avatar.jpg\" alt=\"\" /></span>\r\n");
      out.write("             ");

              Member dto = (Member)session.getAttribute("loginMember");
              String id = (String)session.getAttribute("nick");

            if (dto == null) {
            
      out.write("\r\n");
      out.write("            <h1 id=\"title\">로그인을 해주세요</h1>\r\n");
      out.write("            ");

            } else {
               
      out.write("<h1 id=\"title\">");
      out.print( dto.getUser_nick() );
      out.write("님 환영합니다.</h1>\r\n");
      out.write("               <p>로그인 환영합니다.</p>\r\n");
      out.write("            ");

            } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- Nav -->\r\n");
      out.write("         <nav id=\"nav\">\r\n");
      out.write("            \r\n");
      out.write("            <ul>\r\n");
      out.write("               <li><a href=\"main.jsp\" id=\"top-link\"><span class=\"icon solid fa-home\">메인</span></a></li>\r\n");
      out.write("               <li><a href=\"delete.jsp\" id=\"about-link\"><span class=\"icon solid fa-user\">회원삭제</span></a></li>\r\n");
      out.write("               ");
 if (dto == null) {
      out.write("\r\n");
      out.write("               <li><a href=\"NewLogin.html\" id=\"about-link\"><span class=\"icon solid fa-user\">로그인 / 회원가입</span></a></li>\r\n");
      out.write("               ");
}  else {
      out.write("\r\n");
      out.write("               <li><a href=\"update.jsp\" id=\"portfolio-link\"><span class=\"icon solid fa-th\">회원수정</span></a></li>\r\n");
      out.write("               <li><a href=\"Logout\" id=\"about-link\"><span class=\"icon solid fa-user\">로그아웃</span></a></li>\r\n");
      out.write("               ");

                }
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("         </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("	 \r\n");
      out.write("      <div class=\"bottom\">\r\n");
      out.write("\r\n");
      out.write("         <!-- Social Icons -->\r\n");
      out.write("         <ul class=\"icons\">\r\n");
      out.write("            <li><a href=\"#\" class=\"icon brands fa-twitter\"><span\r\n");
      out.write("                  class=\"label\">Twitter</span></a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span\r\n");
      out.write("                  class=\"label\">Facebook</span></a></li>\r\n");
      out.write("            <li><a href=\"https://github.com/2022-SMHRD-KDT-BigData-4/TRAVELARY_first_project\"\r\n");
      out.write("               class=\"icon brands fa-github\"><span class=\"label\">Github</span></a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"icon brands fa-dribbble\"><span\r\n");
      out.write("                  class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"icon solid fa-envelope\"><span\r\n");
      out.write("                  class=\"label\">Email</span></a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   <!-- Main -->\r\n");
      out.write("   <div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Intro -->\r\n");
      out.write("      <section id=\"top\" class=\"one dark cover\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <header>\r\n");
      out.write("               <h2 class=\"alt\">\r\n");
      out.write("                 TRAVELER\r\n");
      out.write("               </h2>\r\n");
      out.write("               \r\n");
      out.write("            </header>\r\n");
      out.write("		<footer>\r\n");
      out.write("								<a href=\"#portfolio\" class=\"button scrolly\">추천글보러가기</a>\r\n");
      out.write("							</footer>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <!-- Portfolio -->\r\n");
      out.write("      <section id=\"portfolio\" class=\"two\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <header>\r\n");
      out.write("               <h2>Where is the best place?</h2>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <p>TOP 6</p>\r\n");
      out.write("<<div class=\"wrap\">\r\n");
      out.write("<<div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA0MTRfMjY4%2FMDAxNjQ5OTEyNTQ2NjEy.zIw5eGRMpExXZESQXe5hyN2cXou0pYIcI6Rngw35KXUg.98t9NwDmPG_DMPOrO9AB51m2ef0DiO4LkGluekn4Om0g.PNG.damsels%2F14.png&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA0MThfNTIg%2FMDAxNjUwMjc3MTAzNDE1.Ygl6JShdSD4qtj3Wkx_xQCfm9yAQ3HOz6ztJ3teQoKcg.lgSgjR-XycPcYtfTPFLaySk1jkekZem6F_msD7Z_jPQg.JPEG.whtnwjd189%2FKakaoTalk_20220418_190925288_02.jpg&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjAxMzBfMjMz%2FMDAxNjQzNDc0MDY5ODQ1.c_plMTqCw53vksT6X3oezv6VqMRbESYp16GK8I-NfUgg.bNxjyul_znbVnhM_K_C6X6TPHDjGGwJkVqkiAieF1IYg.PNG.dunhill2400%2F%25BD%25BA%25C5%25A9%25B8%25B0%25BC%25A6_2022-01-30_%25BF%25C0%25C0%25FC_1.34.26.png&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=https%3A%2F%2Fdbscthumb-phinf.pstatic.net%2F5701_000_40%2F20220329133003557_S49J5YST3.jpg%2FbG92ZWpqaW4yfDM0.jpg%3Ftype%3Dm936&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxODEyMTBfMzAw%2FMDAxNTQ0NDQyMjc4ODMz.--FJ00lqhPzJJmkPgFvfh1-XRM2SkuH9lA8NKVKMVHwg.hsrnUEGQThQVLRC4C5hnD2qFkkYw9IVUvg5my7c7m5Yg.JPEG.sarangzoong%2F20180802_230729_HDR.jpg&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"tile\"> \r\n");
      out.write("  <img src='https://search.pstatic.net/common/?src=http%3A%2F%2Fshop1.phinf.naver.net%2F20220409_296%2F164946348198999PqQ_JPEG%2F8807688541_1184993673.jpg_1200x1200.jpg&type=sc960_832'/>\r\n");
      out.write("  <div class=\"text\">\r\n");
      out.write("  <h1>테스트 1</h1>\r\n");
      out.write("  <h2 class=\"animate-text\">테스트 1 입니다.</h2>\r\n");
      out.write("  <p class=\"animate-text\">테스트 1 입니다.~~~~</p>\r\n");
      out.write("<div class=\"dots\">\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("    <span></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("            \r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("      <!-- About Me -->\r\n");
      out.write("      <section id=\"about\" class=\"three\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <header>\r\n");
      out.write("               <h2>기능소개</h2>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"#\" class=\"image featured\"><img src=\"images/pic08.jpg\"\r\n");
      out.write("               alt=\"\" /></a>\r\n");
      out.write("\r\n");
      out.write("            <p>기능 소개란.</p>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("      <!-- Contact -->\r\n");
      out.write("      <section id=\"contact\" class=\"four\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <header>\r\n");
      out.write("               <h2>기능소개</h2>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <p>기능 소개란.</p>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Copyright -->\r\n");
      out.write("      <ul class=\"copyright\">\r\n");
      out.write("         <li>&copy; 봄이 오겠조</li>\r\n");
      out.write("         <li>Design: <a href=\"#\">Spring</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Scripts -->\r\n");
      out.write("   <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
