/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-25 09:16:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.domain.Follow;
import com.smhrd.domain.Marker;
import com.smhrd.domain.MarkerDAO;
import org.apache.ibatis.reflection.SystemMetaObject;
import com.smhrd.domain.Member;
import java.util.List;
import com.smhrd.domain.MemberDAO;

public final class Sfollow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/윤/Web(Server)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GitTest/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1651644713468L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.smhrd.domain.Marker");
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.smhrd.domain.MemberDAO");
    _jspx_imports_classes.add("com.smhrd.domain.Member");
    _jspx_imports_classes.add("com.smhrd.domain.Follow");
    _jspx_imports_classes.add("com.smhrd.domain.MarkerDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<title>봄이 오겠조</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/iconfont.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick/slick-theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/stylesheet.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/jquery.fancybox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("<!--        <link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.min.css\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--For Plugins external css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/plugins.css\" />\r\n");
      out.write("\r\n");
      out.write("<!--Theme custom css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!--Theme Responsive css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/responsive.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".navbar-collapse\">\r\n");
      out.write("	");

	Member dto = (Member) session.getAttribute("loginMember");

	String id = (String) session.getAttribute("user_id");
	
      out.write("\r\n");
      out.write("	<div class='preloader'>\r\n");
      out.write("		<div class='loaded'>&nbsp;</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"culmn\">\r\n");
      out.write("		<header id=\"main_menu\" class=\"header navbar-fixed-top\">\r\n");
      out.write("			<div class=\"main_menu_bg\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"nave_menu\">\r\n");
      out.write("							<nav class=\"navbar navbar-default\">\r\n");
      out.write("								<div class=\"container-fluid\">\r\n");
      out.write("									<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("									<div class=\"navbar-header\">\r\n");
      out.write("										<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("											data-toggle=\"collapse\"\r\n");
      out.write("											data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("											aria-expanded=\"false\">\r\n");
      out.write("											<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("												class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("												class=\"icon-bar\"></span>\r\n");
      out.write("										</button>\r\n");
      out.write("										<a class=\"navbar-brand\" href=\"SMain.jsp\"> <img\r\n");
      out.write("											src=\"assets/images/logo.png\" />\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"collapse navbar-collapse\"\r\n");
      out.write("										id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\r\n");
      out.write("										<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("											<li><a href=\"SMain.jsp\">HOME</a></li>\r\n");
      out.write("											<!-- <li><a href=\"#history\">ABOUT US</a></li>\r\n");
      out.write("                                                <li><a href=\"#portfolio\">PORTFOLIO</a></li>\r\n");
      out.write("                                                <li><a href=\"#pricing\">PRICING</a></li>\r\n");
      out.write("                                                <li><a href=\"#team\">TEAM</a></li>\r\n");
      out.write("                                                <li><a href=\"#blog\">BLOG</a></li>\r\n");
      out.write("                                                <li><a href=\"#contact\">CONTACT</a></li> -->\r\n");
      out.write("											         ");

                      if (dto == null) {
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"NewLogin.html\">Login</a></li>\r\n");
      out.write("                      <li><a href=\"#\" id=\"nologinMyhome\">Myhome</a></li>\r\n");
      out.write("                      <li><a href=\"#\" id=\"nologinpost\">post</a></li>\r\n");
      out.write("                      ");

                      } else {
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"Logout\">Logout</a></li>\r\n");
      out.write("                      <li><a href=\"Smyhome.jsp\">Myhome</a></li>\r\n");
      out.write("                      <li><a href=\"Spost.jsp\">post</a></li>\r\n");
      out.write("                      <li><a href=\"Sprofileselect\">Profile</a></li>\r\n");
      out.write("                      ");

                      }
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"Sfollow.jsp\">Follow</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!--End of header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--home Section -->\r\n");
      out.write("		<section id=\"home\" class=\"home\">\r\n");
      out.write("			<div class=\"overlay\">\r\n");
      out.write("				<div class=\"home_skew_border\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-12 \">\r\n");
      out.write("								<div class=\"main_home_slider text-center\">\r\n");
      out.write("									<div class=\"single_home_slider\">\r\n");
      out.write("										<div class=\"main_home wow fadeInUp\" data-wow-duration=\"700ms\">\r\n");
      out.write("											<h3>who are you, I'm</h3>\r\n");
      out.write("											<h1>Traveler</h1>\r\n");
      out.write("											<div class=\"separator\"></div>\r\n");
      out.write("											<p>지도기반 내 발자취 기록 서비스입니다.</p>\r\n");
      out.write("											<div class=\"home_btn\">\r\n");
      out.write("												<a href=\"Sfollow.jsp\" class=\"btn btn-lg m_t_10\">전체회원조회</a>\r\n");
      out.write("												<a href=\"selectmyfolCon\" class=\"btn btn-default\">내 팔로우확인</a>\r\n");
      out.write("												\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"single_home_slider\">\r\n");
      out.write("										<div class=\"main_home wow fadeInUp\" data-wow-duration=\"700ms\">\r\n");
      out.write("											<h3>두번째 공지</h3>\r\n");
      out.write("											<h1>두번째 공지하기</h1>\r\n");
      out.write("											<div class=\"separator\"></div>\r\n");
      out.write("											<p>안녕하세요 테스트중입니당 ㅎㅎ</p>\r\n");
      out.write("											<div class=\"home_btn\">\r\n");
      out.write("												<a href=\"#\" class=\"btn btn-lg m_t_10\">메인으로 가기</a> <a\r\n");
      out.write("													href=\"#history\" class=\"btn btn-default\">서비스 소개</a>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"scrooldown\">\r\n");
      out.write("						<a href=\"#feature\"><i class=\"fa fa-arrow-down\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section id=\"contact\" class=\"contact\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-12\">\r\n");
      out.write("						<div class=\"contact_contant sections\">\r\n");
      out.write("							<div class=\"head_title text-center\">\r\n");
      out.write("								<h2>전체 회원 목록</h2>\r\n");
      out.write("								<div class=\"subtitle\">팔로우할 회원을 찾아보세요.</div>\r\n");
      out.write("								<div class=\"separator\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- End off Head_title -->\r\n");
      out.write("							<div class=\"row\"></div>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("\r\n");
      out.write("							");

							if (dto == null) {
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							                               로그인을 해주세요.\r\n");
      out.write("							\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<form method=\"post\" action=\"followsearch\">\r\n");
      out.write("								ID : <input type=\"text\" name=\"follow_partner\" id=\"follow_partner\"> \r\n");
      out.write("								<input type=\"submit\" value=\"검색\">\r\n");
      out.write("							</form>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							");

							MemberDAO dao = new MemberDAO();
							List<Member> memberList = dao.selectAll();
							pageContext.setAttribute("memberList", memberList);
							String user_id = (String) session.getAttribute("id");
							System.out.print("뽑힘? : " + memberList.get(0).getUser_id());
							
      out.write("\r\n");
      out.write("							<table class=\"type09\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"cols\">아이디</th>\r\n");
      out.write("										<th scope=\"cols\">닉네임</th>\r\n");
      out.write("										<th scope=\"cols\">상태메세지</th>\r\n");
      out.write("										<th scole=\"cols\">팔로우</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</table>\r\n");
      out.write("							<style>\r\n");
      out.write("form {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 1.3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type09 {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type09 thead th {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	vertixal-align: top;\r\n");
      out.write("	color: #369;\r\n");
      out.write("	border-bottom: 3px solid #036;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type09 tbody th {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("	background: #f3f6f7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type09 td {\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("							<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("							<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("							<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("							<br>\r\n");
      out.write("							<div class=\"col-sm-6\"></div>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End of contact section -->\r\n");
      out.write("	<!--End of home section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--feature section -->\r\n");
      out.write("	<!--  <section id=\"feature\" class=\"feature sections\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_feature text-center\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-3\">\r\n");
      out.write("							<div class=\"single_feature\">\r\n");
      out.write("								<div OnClick=\"location.href ='#history'\" style=\"cursor:pointer;\" class=\"single_feature_icon\">\r\n");
      out.write("									<i class=\"fa fa-clone\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<h4>서비스 소개</h4>\r\n");
      out.write("								<div class=\"separator3\"></div>\r\n");
      out.write("								<p>저희 서비스를 소개해 드릴게요!</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-3\">\r\n");
      out.write("							<div class=\"single_feature\">\r\n");
      out.write("								<div OnClick=\"location.href ='#service'\" style=\"cursor:pointer;\" class=\"single_feature_icon\">\r\n");
      out.write("									<i class=\"fa fa-heart-o\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<h4>기능 소개</h4>\r\n");
      out.write("								<div class=\"separator3\"></div>\r\n");
      out.write("								<p>서비스의 기능을 소개해 드릴게요!</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-3\">\r\n");
      out.write("							<div class=\"single_feature\">\r\n");
      out.write("								<div OnClick=\"location.href ='#portfolio'\" style=\"cursor:pointer;\" class=\"single_feature_icon\">\r\n");
      out.write("									<i class=\"fa fa-lightbulb-o\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4>BEST POST</h4>\r\n");
      out.write("								<div class=\"separator3\"></div>\r\n");
      out.write("								<p>인기게시물을 확인해 보세요!</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-3\">\r\n");
      out.write("							<div class=\"single_feature\">\r\n");
      out.write("								<div OnClick=\"location.href ='#team'\" style=\"cursor:pointer;\" class=\"single_feature_icon\">\r\n");
      out.write("									<i class=\"fa fa-comments-o\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<h4>팀 소개</h4>\r\n");
      out.write("								<div class=\"separator3\"></div>\r\n");
      out.write("								<p>저희 팀을 소개합니다!</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>-->\r\n");
      out.write("	<!--End of container -->\r\n");
      out.write("	<!--  </section>-->\r\n");
      out.write("	<!--End of feature Section -->\r\n");
      out.write("	<!--  <hr />\r\n");
      out.write("\r\n");
      out.write("<section id=\"contact\" class=\"contact\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-12\">\r\n");
      out.write("						<div class=\"contact_contant sections\">\r\n");
      out.write("							<div class=\"head_title text-center\">\r\n");
      out.write("								<h2>kEEP IN TOUCH</h2>\r\n");
      out.write("								<div class=\"subtitle\">Nullam sit amet odio eu est aliquet\r\n");
      out.write("									euismod a a urna. Proin eu urna suscipit, dictum quam nec.</div>\r\n");
      out.write("								<div class=\"separator\"></div>\r\n");
      out.write("							</div>-->\r\n");
      out.write("	<!-- End off Head_title -->\r\n");
      out.write("	<!-- ><div class=\"row\"></div>\r\n");
      out.write("							지도 넣으셈\r\n");
      out.write("							<div class=\"col-sm-6\"></div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section> --\r\n");
      out.write("		<!-- End of contact section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- History section -->\r\n");
      out.write("	<!--  <section id=\"history\" class=\"history sections\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_history\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<div class=\"single_history_img\">\r\n");
      out.write("								<img src=\"assets/images/stab1.png\" alt=\"\"/>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<div class=\"single_history_content\">\r\n");
      out.write("								<div class=\"head_title\">\r\n");
      out.write("									<h2>서비스 소개</h2>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p id=\"explain\">지도에 당신만의 발자취를 남겨보세요!</p>\r\n");
      out.write("								<p>1. 지도에서 당신이 다녀왔던 장소를 클릭</p>\r\n");
      out.write("								<p>2. 취향대로 마커의 모양 설정</p>\r\n");
      out.write("								<p>3. 장소에 담긴 당신만의 이야기를 입력</p>\r\n");
      out.write("								<p>4. 카테고리별로 발자취 공유</p>\r\n");
      out.write("								<p>5. 팔로우한 친구의 발자취도 따라가볼까요?</p>\r\n");
      out.write("\r\n");
      out.write("								<a href=\"\" class=\"btn btn-lg\">BROWSE OUR WORK</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				End of row\r\n");
      out.write("			</div>\r\n");
      out.write("			End of container\r\n");
      out.write("		</section> -->\r\n");
      out.write("	<!--End of history -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- service Section -->\r\n");
      out.write("	<!--  <section id=\"service\" class=\"service\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_service\">\r\n");
      out.write("						<div class=\"col-md-6 col-sm-12 no-padding\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"single_service single_service_text text-right\">\r\n");
      out.write("								<div class=\"head_title\">\r\n");
      out.write("									<h2>OUR SERVICES</h2>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-md-12 col-sm-10 col-xs-10 margin-bottom-60\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"col-sm-10 col-sm-offset-1 col-xs-9 col-xs-offset-1\">\r\n");
      out.write("												<article class=\"single_service_right_text\">\r\n");
      out.write("													<h4>카카오맵API기반</h4>\r\n");
      out.write("													<p>안전한 API이용</p>\r\n");
      out.write("												</article>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-1 col-xs-1\">\r\n");
      out.write("												<figure class=\"single_service_icon\">\r\n");
      out.write("													<i class=\"fa fa-heart\"></i>\r\n");
      out.write("												</figure>-->\r\n");
      out.write("	<!-- End of figure -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>-->\r\n");
      out.write("	<!-- End of col-sm-12 -->\r\n");
      out.write("\r\n");
      out.write("	<!--  <div class=\"col-md-12 col-sm-10 col-xs-10 margin-bottom-60\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"col-sm-10 col-sm-offset-1 col-xs-9 col-xs-offset-1\">\r\n");
      out.write("												<article class=\"single_service_right_text\">\r\n");
      out.write("													<h4>카테고리별 마커 공유</h4>\r\n");
      out.write("													<p>카테고리별로 자신의 이야기를 공유해 보세요!</p>\r\n");
      out.write("												</article>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-1 col-xs-1\">\r\n");
      out.write("												<figure class=\"single_service_icon\">\r\n");
      out.write("													<i class=\"fa fa-heart\"></i>\r\n");
      out.write("												</figure>-->\r\n");
      out.write("	<!-- End of figure -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>-->\r\n");
      out.write("	<!-- End of col-sm-12 -->\r\n");
      out.write("\r\n");
      out.write("	<!--  <div class=\"col-md-12 col-sm-10 col-xs-10 margin-bottom-60\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"col-sm-10 col-sm-offset-1 col-xs-9 col-xs-offset-1 margin-bottom-20\">\r\n");
      out.write("												<article class=\"single_service_right_text\">\r\n");
      out.write("													<h4>타임라인</h4>\r\n");
      out.write("													<p>팔로우한 친구의 타임라인을 구경해 볼까요?</p>\r\n");
      out.write("												</article>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-1 col-xs-1\">\r\n");
      out.write("												<figure class=\"single_service_icon\">\r\n");
      out.write("													<i class=\"fa fa-heart\"></i>\r\n");
      out.write("												</figure>-->\r\n");
      out.write("	<!-- End of figure -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>-->\r\n");
      out.write("	<!-- End of col-sm-12 -->\r\n");
      out.write("\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>-->\r\n");
      out.write("	<!-- End of col-sm-6 -->\r\n");
      out.write("\r\n");
      out.write("	<!--  <div class=\"col-md-6 col-sm-12 no-padding\">\r\n");
      out.write("							<figure class=\"single_service single_service_img\">\r\n");
      out.write("								<div class=\"overlay-img\"></div>\r\n");
      out.write("								<img src=\"assets/images/servicerightimg.jpg\" alt=\"\" />\r\n");
      out.write("							</figure>-->\r\n");
      out.write("	<!-- End of figure -->\r\n");
      out.write("	<!--  </div>-->\r\n");
      out.write("	<!-- End of col-sm-6 -->\r\n");
      out.write("\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("				</div>-->\r\n");
      out.write("	<!-- End of row -->\r\n");
      out.write("	<!--  </div>-->\r\n");
      out.write("	<!-- End of Container-fluid -->\r\n");
      out.write("	<!--  </section>-->\r\n");
      out.write("	<!-- End of service Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  <section id=\"portfolio\" class=\"portfolio sections\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_portfolio\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<div class=\"head_title text-center\">\r\n");
      out.write("								<h2>BEST POST</h2>\r\n");
      out.write("								<div class=\"subtitle\">인기 게시물을 확인해 보세요!</div>\r\n");
      out.write("								<div class=\"separator\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"work_menu text-center\">\r\n");
      out.write("							<div id=\"filters\" class=\"toolbar mb2 mt2\">\r\n");
      out.write("								<button class=\"btn-md fil-cat filter active\" data-filter=\"all\">ALL</button>\r\n");
      out.write("								/\r\n");
      out.write("								<button class=\"btn-md fil-cat filter\" data-rel=\"web\"\r\n");
      out.write("									data-filter=\".web\">카테고리1</button>\r\n");
      out.write("								/\r\n");
      out.write("								<button class=\"btn-md fil-cat filter\" data-rel=\"design\"\r\n");
      out.write("									data-filter=\".design\">카테고리1</button>\r\n");
      out.write("								/\r\n");
      out.write("								<button class=\"btn-md fil-cat filter\" data-rel=\"flyers\"\r\n");
      out.write("									data-filter=\".flyers\">카테고리1</button>\r\n");
      out.write("								/\r\n");
      out.write("								<button class=\"btn-md fil-cat filter\" data-rel=\"bcards\"\r\n");
      out.write("									data-filter=\".bcards\">카테고리1</button>\r\n");
      out.write("								/-->\r\n");
      out.write("	<!-- <button class=\"btn-md fil-cat filter\" data-rel=\"photo\"\r\n");
      out.write("									data-filter=\".photo\">PHOTOGRAPHY</button>\r\n");
      out.write("								/\r\n");
      out.write("								<button class=\"btn-md fil-cat filter\" data-rel=\"video\"\r\n");
      out.write("									data-filter=\".video\">VIDEO</button> -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"clear: both;\"></div>\r\n");
      out.write("						<div id=\"portfoliowork\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"single_portfolio tile scale-anm web grid-item-width2 video\">\r\n");
      out.write("								<img src=\"assets/images/pf1.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf1.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>글제목1</h3>\r\n");
      out.write("										<p>설명</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm bcards photo\">\r\n");
      out.write("								<img src=\"assets/images/pf2.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf2.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>글제목2</h3>\r\n");
      out.write("										<p>설명</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm web video\">\r\n");
      out.write("								<img src=\"assets/images/pf3.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf3.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>글제목3</h3>\r\n");
      out.write("										<p>설명</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm web photo\">\r\n");
      out.write("								<img src=\"assets/images/pf4.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf4.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("										<p>art / t-shirt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm bcards design\">\r\n");
      out.write("								<img src=\"assets/images/pf5.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf5.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("										<p>art / t-shirt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm flyers video design\">\r\n");
      out.write("								<img src=\"assets/images/pf6.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf6.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("										<p>art / t-shirt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm photo flyers\">\r\n");
      out.write("								<img src=\"assets/images/pf7.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf7.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("										<p>art / t-shirt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"single_portfolio tile scale-anm bcards video\">\r\n");
      out.write("								<img src=\"assets/images/pf8.jpg\" alt=\"\" /> <a\r\n");
      out.write("									href=\"assets/images/pf8.jpg\" class=\"portfolio-img\">\r\n");
      out.write("									<div class=\"grid_item_overlay\">\r\n");
      out.write("										<div class=\"separator4\"></div>\r\n");
      out.write("										<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("										<p>art / t-shirt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"clear: both;\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>-->\r\n");
      out.write("	<!-- End off container -->\r\n");
      out.write("	<!--  </section>-->\r\n");
      out.write("	<!-- End off Work Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Study Section -->\r\n");
      out.write("	<!-- <section id=\"study\" class=\"study text-center wow fadeIn\"\r\n");
      out.write("			data-wow-duration=\"2s\" data-wow-dealy=\"1.5s\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_study_area sections\">\r\n");
      out.write("						<div class=\"head_title text-center\">\r\n");
      out.write("							<h2>CASE STUDY</h2>\r\n");
      out.write("							<div class=\"subtitle\">A brief story about how this process\r\n");
      out.write("								works, keep an eye till the end.</div>\r\n");
      out.write("							<div class=\"separator\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single_study_content\">\r\n");
      out.write("							<div class=\"col-sm-6\">\r\n");
      out.write("								<div class=\"single_study_slid_area\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"single_study_text\">\r\n");
      out.write("										<div class=\"study_slider\">\r\n");
      out.write("											<div class=\"item\">\r\n");
      out.write("												<div class=\"s_study_icon\">\r\n");
      out.write("													<i class=\"fa fa-lightbulb-o\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("												<h4>aCCUMULATE CREATIVE IDEAS</h4>\r\n");
      out.write("												<div class=\"separator3\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting let. Lorem Ipsum has been the industry. Lorem\r\n");
      out.write("													Ipsum is simply dummy text of the printing and typesetting\r\n");
      out.write("													let. Lorem Ipsum has been the industry Printing and\r\n");
      out.write("													typelorem Ipsum has been the setting let.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"btn btn-lg\">read more</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"item\">\r\n");
      out.write("												<div class=\"s_study_icon\">\r\n");
      out.write("													<i class=\"fa fa-lightbulb-o\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("												<h4>aCCUMULATE CREATIVE IDEAS</h4>\r\n");
      out.write("												<div class=\"separator3\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting let. Lorem Ipsum has been the industry. Lorem\r\n");
      out.write("													Ipsum is simply dummy text of the printing and typesetting\r\n");
      out.write("													let. Lorem Ipsum has been the industry Printing and\r\n");
      out.write("													typelorem Ipsum has been the setting let.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"btn btn-lg\">read more</a>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"item\">\r\n");
      out.write("												<div class=\"s_study_icon\">\r\n");
      out.write("													<i class=\"fa fa-lightbulb-o\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("												<h4>aCCUMULATE CREATIVE IDEAS</h4>\r\n");
      out.write("												<div class=\"separator3\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting let. Lorem Ipsum has been the industry. Lorem\r\n");
      out.write("													Ipsum is simply dummy text of the printing and typesetting\r\n");
      out.write("													let. Lorem Ipsum has been the industry Printing and\r\n");
      out.write("													typelorem Ipsum has been the setting let.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"btn btn-lg\">read more</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"single_study_right_img\">\r\n");
      out.write("								<div class=\"col-sm-6\">\r\n");
      out.write("									<div class=\"single_study_img\">\r\n");
      out.write("										<img src=\"assets/images/study.jpg\" alt=\"\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section> -->\r\n");
      out.write("	<!-- End off Study Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Counter Section -->\r\n");
      out.write("	<!-- <section id=\"counter\" class=\"counter\">\r\n");
      out.write("			<div class=\"video_overlay\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<div class=\"main_counter_area text-center\">\r\n");
      out.write("\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"single_counter border_right\">\r\n");
      out.write("										<div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("											<div class=\"single_counter_item\">\r\n");
      out.write("												<i class=\"icon icon-thumbs-up\"></i>\r\n");
      out.write("												<h2 class=\"statistic-counter\">3891</h2>\r\n");
      out.write("												<h4 class=\"\">User Favourites</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"single_counter\">\r\n");
      out.write("										<div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("											<div class=\"single_counter_item\">\r\n");
      out.write("												<i class=\"icon icon-business-3\"></i>\r\n");
      out.write("												<h2 class=\"statistic-counter\">281</h2>\r\n");
      out.write("												<h4 class=\"\">Posts Last 24 Hours</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"single_counter\">\r\n");
      out.write("										<div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("											<div class=\"single_counter_item\">\r\n");
      out.write("												<i class=\"icon icon-people-32\"></i>\r\n");
      out.write("												<h2 class=\"statistic-counter\">618</h2>\r\n");
      out.write("												<h4 class=\"\">Total Posts</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"single_counter\">\r\n");
      out.write("										<div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("											<div class=\"single_counter_item\">\r\n");
      out.write("												<i class=\"icon icon-cup\"></i>\r\n");
      out.write("												<h2 class=\"statistic-counter\">178</h2>\r\n");
      out.write("												<h4 class=\"\">Amazing Features</h4>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div> \r\n");
      out.write("			\r\n");
      out.write("		</section>-->\r\n");
      out.write("	<!-- End of counter section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Pricing Section -->\r\n");
      out.write("	<!--  <section id=\"pricing\" class=\"pricing\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">-->\r\n");
      out.write("	<!-- <div class=\"main_pricing_area sections\">\r\n");
      out.write("						<div class=\"head_title text-center\">\r\n");
      out.write("							<h2>OUR PRICING</h2>\r\n");
      out.write("							<div class=\"subtitle\">A 30 days free trial for all. A brief\r\n");
      out.write("								story about how this process works, keep an eye till the end.</div>\r\n");
      out.write("							<div class=\"separator\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						End off Head_title\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single_pricing\">\r\n");
      out.write("								<div class=\"pricing_head\">\r\n");
      out.write("									<h3>STARTER</h3>\r\n");
      out.write("									<div class=\"pricing_price\">\r\n");
      out.write("										<div class=\"p_r text-center\">$19</div>\r\n");
      out.write("										<div class=\"m_t text-center\">per month</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"pricing_body\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>Competition Analysis Methods</li>\r\n");
      out.write("										<li>All Ranked URLs</li>\r\n");
      out.write("										<li>International Support System</li>\r\n");
      out.write("										<li>Social Media Tracking</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<a href=\"\" class=\"btn btn-md\">CHOOSE PLAN</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						End off col-md-4\r\n");
      out.write("						<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single_pricing pricing_business\">\r\n");
      out.write("								<div class=\"pricing_head \">\r\n");
      out.write("									<h3>PREMIUM</h3>\r\n");
      out.write("									<div class=\"pricing_price\">\r\n");
      out.write("										<div class=\"p_r text-center\">$39</div>\r\n");
      out.write("										<div class=\"m_t text-center\">per month</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"pricing_body\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>Competition Analysis Methods</li>\r\n");
      out.write("										<li>All Ranked URLs</li>\r\n");
      out.write("										<li>International Support System</li>\r\n");
      out.write("										<li>Social Media Tracking</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<a href=\"\" class=\"btn btn-md\">CHOOSE PLAN</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						End off col-md-4\r\n");
      out.write("						<div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("							<div class=\"single_pricing\">\r\n");
      out.write("								<div class=\"pricing_head\">\r\n");
      out.write("									<h3>BUSINESS</h3>\r\n");
      out.write("									<div class=\"pricing_price\">\r\n");
      out.write("										<div class=\"p_r text-center\">$99</div>\r\n");
      out.write("										<div class=\"m_t text-center\">per month</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"pricing_body\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>Competition Analysis Methods</li>\r\n");
      out.write("										<li>All Ranked URLs</li>\r\n");
      out.write("										<li>International Support System</li>\r\n");
      out.write("										<li>Social Media Tracking</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<a href=\"\" class=\"btn btn-md\">CHOOSE PLAN</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						End off col-md-4\r\n");
      out.write("					</div> -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End off row -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End off container -->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End off Pricing Section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Team Section -->\r\n");
      out.write("	<!--  <section id=\"team\" class=\"team\">\r\n");
      out.write("			<div class=\"main_team_area\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<div class=\"head_title textwhite text-center margin-top-80\">\r\n");
      out.write("								<h2>봄이 오겠조</h2>\r\n");
      out.write("								<div class=\"subtitle\">팀명 소개</div>\r\n");
      out.write("								<div class=\"separator\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- End off Head_title -->\r\n");
      out.write("\r\n");
      out.write("	<!--  <div class=\"main_team\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"single_team_img\">\r\n");
      out.write("											<img src=\"assets/images/team1.jpg\" alt=\"\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"single_team_text\">\r\n");
      out.write("											<h4>채상희</h4>\r\n");
      out.write("											<p>Queen</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"single_team_img\">\r\n");
      out.write("											<img src=\"assets/images/team2.jpg\" alt=\"\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"single_team_text\">\r\n");
      out.write("											<h4>김상윤</h4>\r\n");
      out.write("											<p>Talented-Developer</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"single_team_img\">\r\n");
      out.write("											<img src=\"assets/images/team3.jpg\" alt=\"\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"single_team_text\">\r\n");
      out.write("											<h4>김영환</h4>\r\n");
      out.write("											<p>Moodeungsan-makguli</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"single_team_img\">\r\n");
      out.write("											<img src=\"assets/images/team4.jpg\" alt=\"\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"single_team_text\">\r\n");
      out.write("											<h4>김주원</h4>\r\n");
      out.write("											<p></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"single_team_img\">\r\n");
      out.write("											<img src=\"assets/images/test2.jpg\" alt=\"\" />\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"single_team_text\">\r\n");
      out.write("											<h4>정용재</h4>\r\n");
      out.write("											<p>Goo-seol</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>-->\r\n");
      out.write("	<!-- End of main team contant -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("				</div>-->\r\n");
      out.write("	<!-- End of container -->\r\n");
      out.write("	<!--  </div>\r\n");
      out.write("		</section>-->\r\n");
      out.write("	<!-- End off Team Section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Client Logo Section -->\r\n");
      out.write("	<!-- <section id=\"clogo\" class=\"clogo\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_clogo sections text-center\">\r\n");
      out.write("						<div class=\"head_title text-center\">\r\n");
      out.write("							<h2>Great Integrations with Others</h2>\r\n");
      out.write("							<div class=\"subtitle\">Suspendisse sed eros mollis,\r\n");
      out.write("								tincidunt felis eget, interdum erat. Nullam sit amet odio eu est\r\n");
      out.write("								aliquet euismod a a urna. Proin eu urna suscipit, dictum quam\r\n");
      out.write("								nec.</div>\r\n");
      out.write("							<div class=\"separator\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						End off Head_title\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo1.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo2.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo3.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo4.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo5.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo6.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo9.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-3 col-xs-6\">\r\n");
      out.write("							<a href=\"\"><img src=\"assets/images/clogo8.png\" alt=\"\" /></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"divider\"></div>\r\n");
      out.write("		</section> -->\r\n");
      out.write("	<!-- End off clogo Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Blog Section -->\r\n");
      out.write("	<!--   <section id=\"blog\" class=\"blog\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"main_blog sections\">\r\n");
      out.write("						<div class=\"head_title text-center\">\r\n");
      out.write("							<h2>OUR BLOG</h2>\r\n");
      out.write("							<div class=\"subtitle\">Suspendisse sed eros mollis,\r\n");
      out.write("								tincidunt felis eget, interdum eratullam sit amet odio.</div>\r\n");
      out.write("							<div class=\"separator\"></div>\r\n");
      out.write("						</div>-->\r\n");
      out.write("	<!-- End off Head_title -->\r\n");
      out.write("\r\n");
      out.write("	<!--  <div class=\"main_blog_content\">\r\n");
      out.write("							<div class=\"col-sm-6\">\r\n");
      out.write("								<div class=\"single_blog_area textwhite\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-sm-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_img\">\r\n");
      out.write("												<img src=\"assets/images/blog1.jpg\" alt=\"\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-sm-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_text s_b_left\">\r\n");
      out.write("												<p>art/t-shirt</p>\r\n");
      out.write("												<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("												<div class=\"separator2\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting industry. Lorem Ipsum has been the indu Stry's\r\n");
      out.write("													standard dummy text ever since the 1500s, an unknown\r\n");
      out.write("													printer took a galley of type a scrambled it to make a type\r\n");
      out.write("													specimen book.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"read_more\">Read More >></a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-sm-6\">\r\n");
      out.write("								<div class=\"single_blog_area textwhite\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-sm-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_img\">\r\n");
      out.write("												<img src=\"assets/images/blog2.jpg\" alt=\"\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-sm-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_text s_b_left\">\r\n");
      out.write("												<p>art/t-shirt</p>\r\n");
      out.write("												<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("												<div class=\"separator2\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting industry. Lorem Ipsum has been the indu Stry's\r\n");
      out.write("													standard dummy text ever since the 1500s, an unknown\r\n");
      out.write("													printer took a galley of type a scrambled it to make a type\r\n");
      out.write("													specimen book.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"read_more\">Read More >></a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-6\">\r\n");
      out.write("								<div class=\"single_blog_area textwhite\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-sm-6 col-sm-push-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_img\">\r\n");
      out.write("												<img src=\"assets/images/blog3.jpg\" alt=\"\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-sm-6 col-sm-pull-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_text s_b_right\">\r\n");
      out.write("												<p>art/t-shirt</p>\r\n");
      out.write("												<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("												<div class=\"separator2\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting industry. Lorem Ipsum has been the indu Stry's\r\n");
      out.write("													standard dummy text ever since the 1500s, an unknown\r\n");
      out.write("													printer took a galley of type a scrambled it to make a type\r\n");
      out.write("													specimen book.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"read_more\">Read More >></a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-sm-6\">\r\n");
      out.write("								<div class=\"single_blog_area textwhite\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-sm-6 col-sm-push-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_img\">\r\n");
      out.write("												<img src=\"assets/images/blog4.jpg\" alt=\"\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-sm-6 col-sm-pull-6 no-padding\">\r\n");
      out.write("											<div class=\"single_blog_text s_b_right\">\r\n");
      out.write("												<p>art/t-shirt</p>\r\n");
      out.write("												<h3>T-SHIRT DESIGN</h3>\r\n");
      out.write("												<div class=\"separator2\"></div>\r\n");
      out.write("												<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("													typesetting industry. Lorem Ipsum has been the indu Stry's\r\n");
      out.write("													standard dummy text ever since the 1500s, an unknown\r\n");
      out.write("													printer took a galley of type a scrambled it to make a type\r\n");
      out.write("													specimen book.</p>\r\n");
      out.write("\r\n");
      out.write("												<a href=\"\" class=\"read_more\">Read More >></a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>-->\r\n");
      out.write("	<!-- End off Blog Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  <section id=\"trial\" class=\"trial text-center wow fadeIn\"\r\n");
      out.write("			data-wow-duration=\"2s\" data-wow-dealy=\"1.5s\">\r\n");
      out.write("			<div class=\"main_trial_area\">\r\n");
      out.write("				<div class=\"video_overlay sections\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"main_trial\">\r\n");
      out.write("								<div class=\"col-sm-12\">\r\n");
      out.write("									<h2>\r\n");
      out.write("										let's go <span>together !</span>\r\n");
      out.write("									</h2>\r\n");
      out.write("									<h4>A space for all memories</h4>\r\n");
      out.write("									<a href=\"\" class=\"btn btn-lg\">- Traveler</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>-->\r\n");
      out.write("	<!-- End of Trial section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--Footer section-->\r\n");
      out.write("	<section class=\"footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-12\">\r\n");
      out.write("					<div class=\"main_footer\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("								<div class=\"flowus\">\r\n");
      out.write("									<a href=\"\"><i class=\"fa fa-facebook\"></i></a> <a href=\"\"><i\r\n");
      out.write("										class=\"fa fa-twitter\"></i></a> <a href=\"\"><i\r\n");
      out.write("										class=\"fa fa-google-plus\"></i></a> <a href=\"\"><i\r\n");
      out.write("										class=\"fa fa-instagram\"></i></a> <a href=\"\"><i\r\n");
      out.write("										class=\"fa fa-youtube\"></i></a> <a href=\"\"><i\r\n");
      out.write("										class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("								<div class=\"copyright_text\">\r\n");
      out.write("									<p class=\" wow fadeInRight\" data-wow-duration=\"1s\">\r\n");
      out.write("										Made with <i class=\"fa fa-heart\"></i> by <a href=\"#\">봄이오겠조</a>2022.\r\n");
      out.write("										1차프로젝트\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End off footer Section-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- START SCROLL TO TOP  -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"scrollup\">\r\n");
      out.write("		<a href=\"#\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.masonry.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!--slick slide js -->\r\n");
      out.write("	<script src=\"assets/css/slick/slick.js\"></script>\r\n");
      out.write("	<script src=\"assets/css/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Sfollow.jsp(235,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("mb");
      // /Sfollow.jsp(235,8) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Sfollow.jsp(235,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<tr>\r\n");
            out.write("										<th scope=\"row\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("										</td>\r\n");
            out.write("										<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("										<td>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("										<td><a\r\n");
            out.write("											href=\"insertFolCon?follow_partner=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mb.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&follow=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">추가</a></td>\r\n");
            out.write("									</tr>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /Sfollow.jsp(237,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mb.user_id }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /Sfollow.jsp(239,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mb.user_nick }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /Sfollow.jsp(240,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mb.user_status }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }
}
