/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-25 10:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.domain.Follow;
import com.smhrd.domain.FollowDAO;
import com.smhrd.domain.Marker;
import com.smhrd.domain.Member;
import com.smhrd.domain.MemberDAO;
import com.smhrd.domain.MarkerDAO;
import org.apache.ibatis.reflection.SystemMetaObject;
import java.util.List;
import com.smhrd.domain.martest;
import com.smhrd.domain.martestDAO;

public final class Sfolhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.smhrd.domain.FollowDAO");
    _jspx_imports_classes.add("com.smhrd.domain.Marker");
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.smhrd.domain.MemberDAO");
    _jspx_imports_classes.add("com.smhrd.domain.Member");
    _jspx_imports_classes.add("com.smhrd.domain.martestDAO");
    _jspx_imports_classes.add("com.smhrd.domain.Follow");
    _jspx_imports_classes.add("com.smhrd.domain.MarkerDAO");
    _jspx_imports_classes.add("com.smhrd.domain.martest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<title>봄이 오겠조</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/iconfont.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/slick/slick-theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/stylesheet.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/jquery.fancybox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("<!--        <link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.min.css\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--For Plugins external css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/plugins.css\" />\r\n");
      out.write("\r\n");
      out.write("<!--Theme custom css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!--Theme Responsive css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/responsive.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".navbar-collapse\">\r\n");

   Member dto = (Member) session.getAttribute("loginMember");

   String id = (String)session.getAttribute("user_id");
   
      out.write("\r\n");
      out.write("	<div class='preloader'>\r\n");
      out.write("		<div class='loaded'>&nbsp;</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"culmn\">\r\n");
      out.write("		<header id=\"main_menu\" class=\"header navbar-fixed-top\">\r\n");
      out.write("			<div class=\"main_menu_bg\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"nave_menu\">\r\n");
      out.write("							<nav class=\"navbar navbar-default\">\r\n");
      out.write("								<div class=\"container-fluid\">\r\n");
      out.write("									<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("									<div class=\"navbar-header\">\r\n");
      out.write("										<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("											data-toggle=\"collapse\"\r\n");
      out.write("											data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("											aria-expanded=\"false\">\r\n");
      out.write("											<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("												class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("												class=\"icon-bar\"></span>\r\n");
      out.write("										</button>\r\n");
      out.write("										<a class=\"navbar-brand\" href=\"SMain.jsp\"> <img\r\n");
      out.write("											src=\"assets/images/logo.png\" />\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"collapse navbar-collapse\"\r\n");
      out.write("										id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\r\n");
      out.write("										<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("											<li><a href=\"SMain.jsp\">HOME</a></li>\r\n");
      out.write("											<!-- <li><a href=\"#history\">ABOUT US</a></li>\r\n");
      out.write("                                                <li><a href=\"#portfolio\">PORTFOLIO</a></li>\r\n");
      out.write("                                                <li><a href=\"#pricing\">PRICING</a></li>\r\n");
      out.write("                                                <li><a href=\"#team\">TEAM</a></li>\r\n");
      out.write("                                                <li><a href=\"#blog\">BLOG</a></li>\r\n");
      out.write("                                                <li><a href=\"#contact\">CONTACT</a></li> -->\r\n");
      out.write("											          ");

                      if (dto == null) {
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"NewLogin.html\">Login</a></li>\r\n");
      out.write("                      <li><a href=\"#\" id=\"nologinMyhome\">Myhome</a></li>\r\n");
      out.write("                      <li><a href=\"#\" id=\"nologinpost\">post</a></li>\r\n");
      out.write("                      ");

                      } else {
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"Logout\">Logout</a></li>\r\n");
      out.write("                      <li><a href=\"Smyhome.jsp\">Myhome</a></li>\r\n");
      out.write("                      <li><a href=\"Spost.jsp\">post</a></li>\r\n");
      out.write("                      <li><a href=\"Sprofileselect\">Profile</a></li>\r\n");
      out.write("                      ");

                      }
                      
      out.write("\r\n");
      out.write("                      <li><a href=\"Sfollow.jsp\">Follow</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</nav>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!--End of header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--home Section -->\r\n");
      out.write("		<section id=\"home\" class=\"home\">\r\n");
      out.write("			<div class=\"overlay\">\r\n");
      out.write("				<div class=\"home_skew_border\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-12 \">\r\n");
      out.write("								<div class=\"main_home_slider text-center\">\r\n");
      out.write("									<div class=\"single_home_slider\">\r\n");
      out.write("										<div class=\"main_home wow fadeInUp\" data-wow-duration=\"700ms\">\r\n");
      out.write("											<h3>who are you, I'm</h3>\r\n");
      out.write("											<h1>Traveler</h1>\r\n");
      out.write("											<div class=\"separator\"></div>\r\n");
      out.write("											<p>지도기반 내 발자취 기록 서비스입니다.</p>\r\n");
      out.write("											<div class=\"home_btn\">\r\n");
      out.write("												<a href=\"SMain.jsp\" class=\"btn btn-lg m_t_10\">메인화면</a>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"single_home_slider\">\r\n");
      out.write("										<div class=\"main_home wow fadeInUp\" data-wow-duration=\"700ms\">\r\n");
      out.write("											<h3>두번째 공지</h3>\r\n");
      out.write("											<h1>두번째 공지하기</h1>\r\n");
      out.write("											<div class=\"separator\"></div>\r\n");
      out.write("											<p>안녕하세요 테스트중입니당 ㅎㅎ</p>\r\n");
      out.write("											<div class=\"home_btn\">\r\n");
      out.write("												<a href=\"#\" class=\"btn btn-lg m_t_10\">발자취 남기러가기</a> <a\r\n");
      out.write("													href=\"#history\" class=\"btn btn-default\">서비스 소개</a>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"scrooldown\">\r\n");
      out.write("						<a href=\"#feature\"><i class=\"fa fa-arrow-down\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("	<section id=\"contact\" class=\"contact\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-12\">\r\n");
      out.write("						<div class=\"contact_contant sections\">\r\n");
      out.write("							<div class=\"head_title text-center\">\r\n");
      out.write("								<h2>타임라인</h2>\r\n");
      out.write("								<div class=\"subtitle\">마커를 모아 당신만의 타임라인을 확인해 보세요.</div>\r\n");
      out.write("								<div class=\"separator\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- End off Head_title -->\r\n");
      out.write("							<div class=\"row\"></div>\r\n");
      out.write("							\r\n");
      out.write("<!-- 지도 부분 시작 -->	\r\n");
      out.write("<!-- 달력 input -->	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <form method=\"post\" action=\"selectMarCon\">\r\n");
      out.write("      <p><input type=\"date\" min=\"1800-09-10\" max=\"3000-09-25\" name=\"date\"></p>\r\n");
      out.write("      <p><input type=\"submit\" value=\"조회\"></p>\r\n");
      out.write("      </form>	\r\n");
      out.write("<style>\r\n");
      out.write("      \r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -0.3%;\r\n");
      out.write("    left: 112%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<br><br><br><br><br>\r\n");
 String follow_id = (String)session.getAttribute("user_id");
FollowDAO followdao = new FollowDAO();
List<Follow> selectfollower = (List)followdao.selectFollower(follow_id);
session.setAttribute("selectfollower", selectfollower);
System.out.println("사이즈 : "+ selectfollower.size());
System.out.print(selectfollower.get(1).getFollow_partner());
      out.write("   \r\n");
      out.write("	 \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<div class=\"tableDiv\">\r\n");
      out.write("<table class=\"type09\">\r\n");
      out.write("				<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th scope=\"cols\" id=\"id\">친구 아이디</th>\r\n");
      out.write("					<th scope=\"cols\" id=\"timeline\">타임라인</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				\r\n");
      out.write("				");
 for(int i=0; i<selectfollower.size(); i++)  {
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("				<th scope=\"row\">");
      out.print(selectfollower.get(i).getFollow_partner());
      out.write("</td>\r\n");
      out.write("				<td><a href=\"selectFolMar?user_id=");
      out.print(selectfollower.get(i).getFollow_partner());
      out.write("\">보기</a></td>\r\n");
      out.write("				</tr>");
}; 
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<br><br><br><br><br><br><br><br>\r\n");
      out.write(" </div>\r\n");
      out.write("   				\r\n");
      out.write("   				<style>\r\n");
      out.write("   				\r\n");
      out.write("   				form {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 5.6%;\r\n");
      out.write("    top: 55%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   				table.type09 {\r\n");
      out.write("   				border-collapse: collapse;\r\n");
      out.write("   				text-align: left;\r\n");
      out.write("   				line-height: 1.5;\r\n");
      out.write("   				}\r\n");
      out.write("   				\r\n");
      out.write("   				table.type09 thead #id {\r\n");
      out.write("   				padding: 10px;\r\n");
      out.write("   				font-weight: bold;\r\n");
      out.write("   				vertixal-align: top;\r\n");
      out.write("   				color: #369;\r\n");
      out.write("   				border-bottom: 3px solid #036;\r\n");
      out.write("   				}\r\n");
      out.write("   				table.type09 thead #timeline {\r\n");
      out.write("   				padding: 10px;\r\n");
      out.write("   				font-weight: bold;\r\n");
      out.write("   				vertixal-align: top;\r\n");
      out.write("   				color: #369;\r\n");
      out.write("   				border-bottom: 3px solid #036;\r\n");
      out.write("   				}\r\n");
      out.write("   				\r\n");
      out.write("   				table.type09 tbody th {\r\n");
      out.write("    width: 194px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("    background: #f3f6f7;\r\n");
      out.write("}\r\n");
      out.write("   				\r\n");
      out.write("   				table.type09 td {\r\n");
      out.write("    width: 215px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("   				</style>\r\n");
      out.write("   				\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<div id=\"map\" style=\"width:100%;height:500px;\"></div>       \r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=4b2438cac030698bc148f62a014733b9\"></script>  \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var positions = [];						\r\n");
      out.write("var linePath = [];\r\n");
      out.write("var shapes = [];\r\n");
      out.write("var images = [];\r\n");
      out.write("\r\n");
  List<Marker> folMarkerList = (List)session.getAttribute("folMarkerList");
	
 
	System.out.print(folMarkerList.get(0).getLATITUDE() + " " + folMarkerList.get(0).getLONGITUDE()); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = { \r\n");
      out.write("    center: new kakao.maps.LatLng(");
      out.print(folMarkerList.get(0).getLATITUDE());
      out.write(',');
      out.write(' ');
      out.print(folMarkerList.get(0).getLONGITUDE());
      out.write("), // 지도의 중심좌표\r\n");
      out.write("    level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 선을 구성하는 좌표 배열입니다. 이 좌표들을 이어서 선을 표시합니다\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 for(int i = 0; i<folMarkerList.size()-1; i++) { 
      out.write("\r\n");
      out.write("linePath.push(new kakao.maps.LatLng(");
      out.print(folMarkerList.get(i).getLATITUDE());
      out.write(',');
      out.write(' ');
      out.print(folMarkerList.get(i).getLONGITUDE());
      out.write("))\r\n");
};
      out.write("\r\n");
      out.write("\r\n");
 for(int i =0; i<folMarkerList.size()-1; i++) {
      out.write("\r\n");
      out.write("positions.push({title: '");
      out.print(folMarkerList.get(i).getMarker_seq());
      out.write("', latlng: new kakao.maps.LatLng(");
      out.print(folMarkerList.get(i).getLATITUDE());
      out.write(',');
      out.write(' ');
      out.print(folMarkerList.get(i).getLONGITUDE());
      out.write(")})\r\n");
};
      out.write("\r\n");
      out.write("\r\n");
 for(int i =0; i<folMarkerList.size()-1; i ++) {
      out.write("\r\n");
      out.write("shapes.push(");
      out.print(folMarkerList.get(i).getMarker_shape());
      out.write(')');
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* for(var i =0; i<shapes.length; i++) {\r\n");
      out.write("	console.log(shapes[i] + \" // \" )} */\r\n");
      out.write("//담긴 거 확인(완)\r\n");
      out.write("//console.log(shapes)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("for(var i =0; i<shapes.length; i++) {\r\n");
      out.write("	if(shapes[i] == '1') {\r\n");
      out.write("		images.push(\"https://cdn4.iconfinder.com/data/icons/navigation-and-location-5/100/location-11-256.png\")\r\n");
      out.write("	}else if(shapes[i] == '2') {\r\n");
      out.write("		images.push(\"https://cdn3.iconfinder.com/data/icons/free-mix/128/business_office_seo_finance_work_coffee_pause_management-09-2-256.png\")\r\n");
      out.write("	}else if(shapes[i] == '3') {\r\n");
      out.write("		images.push(\"https://cdn3.iconfinder.com/data/icons/food-delivery-4/64/31_food_delivery_restaurant_eat-256.png\")\r\n");
      out.write("	}else if(shapes[i] == '4') {\r\n");
      out.write("		images.push(\"https://cdn3.iconfinder.com/data/icons/animal-40/128/Animal_Dog-256.png\")\r\n");
      out.write("	}else if(shapes[i] == '5') {\r\n");
      out.write("		images.push(\"https://cdn2.iconfinder.com/data/icons/basic-flat-icon-set/128/plane-256.png\")\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/* for(var i =0; i<shapes.length; i++) {\r\n");
      out.write("console.log(images[i] + \" // \" )} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//지도에 표시할 선을 생성합니다\r\n");
      out.write("var polyline = new kakao.maps.Polyline({\r\n");
      out.write(" path: linePath, // 선을 구성하는 좌표배열 입니다\r\n");
      out.write(" strokeWeight: 2, // 선의 두께 입니다\r\n");
      out.write(" strokeColor: '#ea0000', // 선의 색깔입니다\r\n");
      out.write(" strokeOpacity: 0.7, // 선의 불투명도 입니다 1에서 0 사이의 값이며 0에 가까울수록 투명합니다\r\n");
      out.write(" strokeStyle: 'solid' // 선의 스타일입니다\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//지도에 선을 표시합니다 \r\n");
      out.write("polyline.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("for (var i = 0; i < positions.length; i ++) {\r\n");
      out.write("    \r\n");
      out.write("    // 마커 이미지의 이미지 크기 입니다\r\n");
      out.write("    var imageSize = new kakao.maps.Size(24, 35); \r\n");
      out.write("    var markerImage = new kakao.maps.MarkerImage(images[i], imageSize); \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    // 마커를 생성합니다\r\n");
      out.write("    var marker = new kakao.maps.Marker({\r\n");
      out.write("        map: map, // 마커를 표시할 지도\r\n");
      out.write("        position: positions[i].latlng, // 마커를 표시할 위치\r\n");
      out.write("        title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다\r\n");
      out.write("        image : markerImage // 마커 이미지 \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-sm-6\"></div>\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("			</div></div></div></div>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		<section class=\"footer\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-12\">\r\n");
      out.write("						<div class=\"main_footer\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("									<div class=\"flowus\">\r\n");
      out.write("										<a href=\"\"><i class=\"fa fa-facebook\"></i></a> <a href=\"\"><i\r\n");
      out.write("											class=\"fa fa-twitter\"></i></a> <a href=\"\"><i\r\n");
      out.write("											class=\"fa fa-google-plus\"></i></a> <a href=\"\"><i\r\n");
      out.write("											class=\"fa fa-instagram\"></i></a> <a href=\"\"><i\r\n");
      out.write("											class=\"fa fa-youtube\"></i></a> <a href=\"\"><i\r\n");
      out.write("											class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"col-sm-6 col-xs-12\">\r\n");
      out.write("									<div class=\"copyright_text\">\r\n");
      out.write("										<p class=\" wow fadeInRight\" data-wow-duration=\"1s\">\r\n");
      out.write("											Made with <i class=\"fa fa-heart\"></i> by <a href=\"#\">봄이오겠조</a>2022.\r\n");
      out.write("											1차프로젝트\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- End off footer Section-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- START SCROLL TO TOP  -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"scrollup\">\r\n");
      out.write("		<a href=\"#\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.masonry.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!--slick slide js -->\r\n");
      out.write("	<script src=\"assets/css/slick/slick.js\"></script>\r\n");
      out.write("	<script src=\"assets/css/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
